language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-static-scaffold' ]; then cd .. && eval "mv $currentfolder generator-static-scaffold" && cd generator-static-scaffold; fi

